server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.20.128
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  sms:
    accessKeyId: LTAIf5vJTEe70iPa    # 你自己的accessKeyId
    accessKeySecret: A2ZGBWfrkz9arF908cmDWXmIrAlngA # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称